### ISSUE TITLE
상품 상세, 마켓 상세 화면 View UI 구현

### ISSUE THREAD

**Issue by thisisdana49** [Bloom-DSB/Bloom-iOS#15]
## 설명
- 마켓 및 상품 상세 전체 UI를 구현한다.

## 화면
- 마켓 상세
- 상품 상세

## 스토리
02. 사용자는 마켓의 상세 정보를 확인할 수 있어야 한다.
04. 사용자는 상품의 상세 정보를 확인할 수 있어야 한다.

## 요구사항
- 마켓 상세 화면 View를 생성하고 전체 UI를 구현한다.
- 상품 상세 화면 View를 생성하고 전체 UI를 구현한다.

## 기타사항 (optional)
- 우선순위가 높으므로 먼저 작업한다.

**Comment by WaterBean** [comment]
이미지뷰 safe area ignore가 필요합니다! 이슈확인 하고 마무리 부탁드려요~
