### ISSUE TITLE
iOS 레포지토리 .gitignore 생성

### ISSUE THREAD

**Issue by WaterBean** [Bloom-DSB/Bloom-iOS#2]
## 설명
- iOS 레포지토리 .gitignore 생성

## 스토리
- 0. 공통 개발 환경을 설정한다. 

## 요구사항
- conflict를 방지할 수 있도록 구성한다.
- 프로젝트 관련된 파일만 업로드 될 수 있도록 구성한다.

**Comment by thisisdana49** [comment]
.gitignore 추가 완료하여 Issue Close하겠습니다.

**Comment by WaterBean** [comment]
xcodeproj 파일을 포함시켜 다시 커밋 부탁드립니다.

**Comment by WaterBean** [comment]
새로운 이슈 생성으로 인해 close #10
