### ISSUE TITLE
프로젝트 초기 세팅

### ISSUE THREAD

**Issue by WaterBean** [Bloom-DSB/Bloom-iOS#3]
## 설명
- 프로젝트 초기 세팅 이슈

## 화면
- 공통

## 스토리
- 00. 공통 개발 환경을 설정한다.

## 요구사항
- 프로젝트 파일 설정
- 폴더 구조 설정
- Color Scheme, Package Dependencies 추가

## 기타사항 (optional)
- 마크다운 문서로 건드린 설정 기록해주세요.

**Comment by WaterBean** [comment]
xcodeproject 파일이 존재하지 않아서 프로젝트를 열어볼 수 없습니다! #2 에서 설정한 .gitignore 파일을 다시 확인해서 커밋 부탁드립니다.

**Comment by thisisdana49** [comment]
xcodeproject conflict 관련해서 링크 전달 드립니다. 어떻게 해야할지 논의해야할 부분인 것 같아 전달 드립니다.

https://vapor3965.tistory.com/100

**Comment by thisisdana49** [comment]
관련 링크 하나 더 전달 드립니다! 이 블로그에 의하면  당연하게 겪을 수 밖에 없는...이라고 해서,
일단은 gitignore에서 xcodeproject를 제외하는 방향으로 하고 이후 충돌이 일어난다면 해결해 보는 것이 좋을 것 같습니다.

https://didu-story.tistory.com/373
